### ISSUE TITLE
Crash due to blockcypher

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-api-publish#11]
```
/home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/lib/bcypher.js:427
		cb(error, body);
		^

TypeError: cb is not a function
    at /home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/lib/bcypher.js:427:3
    at /home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/lib/bcypher.js:40:9
    at Request.callback (/home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/node_modules/superagent/lib/node/index.js:716:12)
    at parser (/home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/node_modules/superagent/lib/node/index.js:916:18)
    at Stream.res.on (/home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at emitNone (events.js:106:13)
    at Stream.emit (events.js:208:7)
    at Unzip.unzip.on (/home/fazo/Documents/Projects/chlu-api-publish/node_modules/blockcypher/node_modules/superagent/lib/node/unzip.js:55:12)
    at emitNone (events.js:111:20)
    at Unzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by fazo96** [comment]
Fixed in chlu-ipfs 0.3.1
